### ISSUE TITLE
About the reset pose of the common skeleton

### ISSUE THREAD

**Issue by Shimingyi** [orangeduck/lafan1-resolved#2]
Hi,

I observed the T-pose in the common skeleton appears somewhat unusual and would like to delve deeper into this issue.

As we know, motion data is built upon the rest pose, where joint rotations represent the local joint orientation relative to the specified T-pose. Then if the T-pose is different in the training and testing, basically we will need some manual adjustment to ensure the consistency. 

But just now, I downloaded the retargeted motion from this repo, and found the rest pose in these data is kindly weird; also there is no standard T-pose in any frames, which made some troubling for the further skinning. 

Many people complained about the variations in T-poses across different datasets, such as CMU, Lafan, and others. Each time I work with new motion data from these datasets, I find myself manually adjusting the T-pose. Is there a more efficient way to manage these discrepancies or perhaps a **unified** practice for defining the T-pose?

<img width="1531" alt="Different T-pose across motion datasets" src="https://github.com/user-attachments/assets/2b4f7398-603d-4432-bb8f-262c34040503">

**Comment by orangeduck** [comment]
Hi @Shimingyi

Great observation. Thanks for bringing this up.

Here are my rough thoughts on the topic...

First of all, I would not call these "T-poses" or "rest poses". These are the pose you get when you set all of the rotations in the skeleton to the identity rotation - so personally I think a better name for them is "identity poses". And in most cases the "identity pose" is not actually useful for much. It's just an artifact of how the skeleton articulation is chosen.

In fact, I think things are clearer if we list out all of the important default poses involved in character animation.

* The "identity pose". This is the aforementioned pose you get when you set all of the local rotations to the identity rotation. As you show above... this a meaningless pose for this skeleton when examined visually.
* The "bind pose". This is the pose the skeleton was in when it was skinned to a particular skinned mesh. For example, if you want to see the bind pose I used for this Geno character you can find it by opening the Maya file I used [here](https://github.com/orangeduck/GenoView/blob/main/resources/Geno.mb). This is the pose of the skeleton which corresponds to the vertex data for the mesh stored in the game. While the bind pose can typically be anything. It is very common these days to have it be a relaxed natural pose with the arms down slightly, the knees a little bent, and the spine in a natural upright position a.k.a. an "A-Pose".  ![image](https://github.com/user-attachments/assets/f43010a5-84a1-4b7a-9129-6e2d7fed39de)
* The "stance pose". This is the pose used when retargeting from one skeleton to another. Again, while this pose can technically be anything (as long as it is consistent between characters). In MotionBuilder this pose must have the legs straight down, the spine straight up, and the arms straight out. This is the most common "T-Pose" people are usually referring to. If you want to see this open [Geno.fbx](https://github.com/orangeduck/lafan1-resolved/blob/main/Geno.fbx) in MotionBuilder and make sure the Geno Character Input Type is set to "Stance". ![image](https://github.com/user-attachments/assets/aa555ff1-49ed-4f18-8ed0-000b5c846ae3)
* The "average pose". This is the pose you get when you take the average of the local joint rotations over some animation dataset. Typically this has the character slightly hunched over with the knees bent and the arms bent and slightly inward. Sometimes this is called the "fetus-pose".

Note that none of the "stance pose", the "bind pose", or the "average pose" may be necessarily the same as the "identity pose". While it may be possible to make it so that the "identity pose" is the same as one of the other poses by constructing your skeleton carefully, there are often good reasons not to do so (for example, you may want bone translations to by default always be a simple forward translation on X - giving you a skeleton like Lafan).

However like you say, when you are retargeting between skeletons you need to have some consistent pose for your two skeletons to be able to find the correspondence. In MotionBuilder this is the "stance pose" and so probably the closest to an industry standard. If you want to retarget using MotionBuilder's "stance pose" there is no way around that you may need to manually pose your skeleton into this pose.

But in theory we can retarget using any pose as long as it is consistent between skeletons. If we are determined to compute the retargeting reference pose automatically we can consider our other options.

For example - if I have two skeletons skinned to the same mesh, we could use their "bind pose" as the reference pose for retargeting. As this will (almost by definition) be the same pose on both skeletons.

Or, if we have a large datasets of animation data on both our skeletons, we could also consider using the "average pose" as the reference pose for retargeting. If the data is large and varied enough we should expect this "average pose" to average out to the same thing for both skeletons.

Hope that helps,

Dan

**Comment by Shimingyi** [comment]
Hi Dan,

Thanks so much for the detailed explanation, it has been very helpful for our discussions.

In practice, the "bind pose" and "stance pose" hold more significance compared to the "identity pose". However, these two crucial poses are often not directly present in the original BVH files. If someone intends to utilize the motion data for other purposes, they will need to manually create these poses, whether for skinning or retargeting. This manual process introduces kind of uncertainty (For example, different A-pose problem).

I understand that the "stance pose" and the "bind pose" do not necessarily have to match the "identity pose". But in this context, why not designate them as the "identity pose" for easier access instead of requiring manual intervention? For example, the x-forwarding identity pose in Lafan dataset has not proven useful in my scenario, but it complicates the preprocessing stage when integrating it into my existing motion dataset. It also poses challenges for people who are not well-versed in basic motion processing (refer to the issue in the original repository: [issue](https://github.com/ubisoft/ubisoft-laforge-animation-dataset/issues/8)). If it has the "stance pose" as identity, then what's the risk?

It will be more appreciate if motion data could to be universal or open-use as image in vision task. Until now, I still need an extra folder called "rawdata_processed" in my workspace for passing the datasets one by one. A better standard or practice will be much much helpful.

Best,
Mingyi

**Comment by orangeduck** [comment]
Hi Mingyi,

Yes I think those are fair points. In the very least I will add both the stance pose and the bind pose to all of these repos in fbx and bvh format to help people out.

Thanks,

Dan

**Comment by orangeduck** [comment]
Okay I've added assets for the bind and stance poses. I hope that can help!

**Comment by Shimingyi** [comment]
> Okay I've added assets for the bind and stance poses. I hope that can help!

Thanks for it!
